---
title: "Project 1 Coverage Ratio"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

dfraw <- read_rds("YL_04_coverRatio_ind.rds")

df <- dfraw %>% mutate(trueValue = as.factor(trueValue))

### question 1 two columns
df1 <- df %>% filter(question %>% str_detect("1"))

### question 2 three columns 2 rows
df2 <- df %>% filter(question %>% str_detect("2"))
df2

### three columns, for three trueValue or type

tvals <- df2 %>% pull(trueValue) %>% unique() %>% sort()


### joint data ###
dfjointraw <- read_rds("YL_04_coverRatio_joint.rds")
dfjoint <- dfjointraw %>% mutate(method = as.factor(method))
dfjoint1 <- dfjoint %>% filter(question %>% str_detect("1"))
dfjoint2 <- dfjoint %>% filter(question %>% str_detect("2"))
```

# Question 1 Individual

### Ratio

Q 1a

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.5, 0.3, 0.2)))
```

Q 1b

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.5, 0.48, 0.02)))
```


Row 
-----------------------------------------------------------------------


### 1a Method 1

```{r}

i <- 1
plot_ly(
  data = df1 %>% filter(method == i, trueValue %in% c(0.1, 0.2, 0.3)),
  x = ~sampleSize, y = ~coverRatio, color = ~trueValue,
  type = "bar", name = ~paste("True Value", trueValue)
) %>%
  layout(title = paste("Coverage Ratio for", "Method", i), yaxis = list(title = "Coverage Ratio", range = c(0.9, 1)))
```

### 1b Method 1

```{r}

i <- 1
plot_ly(
  data = df1 %>% filter(method == i, trueValue %in% c(0.02, 0.46, 0.48)),
  x = ~sampleSize, y = ~coverRatio, color = ~trueValue,
  type = "bar", name = ~paste("True Value", trueValue)
) %>%
  layout(title = paste("Coverage Ratio for", "Method", i), yaxis = list(title = "Coverage Ratio", range = c(0.9, 1)))
```

Row
-----------------------------------------------------------------------

### 1a Method 2

```{r}
i <- 2
plot_ly(
  data = df1 %>% filter(method == i, trueValue %in% c(0.1, 0.2, 0.3)),
  x = ~sampleSize, y = ~coverRatio, color = ~trueValue,
  type = "bar", name = ~paste("True Value", trueValue)
) %>%
  layout(title = paste("Coverage Ratio for", "Method", i), yaxis = list(title = "Coverage Ratio", range = c(0.9, 1)))
```

### 1b Method 2

```{r}
i <- 2
plot_ly(
  data = df1 %>% filter(method == i, trueValue %in% c(0.02, 0.46, 0.48)),
  x = ~sampleSize, y = ~coverRatio, color = ~trueValue,
  type = "bar", name = ~paste("True Value", trueValue)
) %>%
  layout(title = paste("Coverage Ratio for", "Method", i), yaxis = list(title = "Coverage Ratio", range = c(0.9, 1)))
```

# Question 1 Joint


### Ratio

Q 1a

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.5, 0.3, 0.2)))
```

Q 1b

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.5, 0.48, 0.02)))
```


Column
-----------------------------------------------------------------------

### Question 1a

```{r}

i <- "1a"
plot_ly(
  data = dfjoint1 %>% filter(question == i),
  x = ~sampleSize, y = ~jointRatio, color = ~method, type = "bar",
  name = ~paste("method", method)) %>%
  layout(title = paste("Joint Coverage Ratio for", "Question", i), 
         yaxis = list(title = "Joint Coverage Ratio", range = c(0.9, 1),dtick = 0.01))
```

Column
-----------------------------------------------------------------------

### Question 1b

```{r}
i <- "1b"
plot_ly(
  data = dfjoint1 %>% filter(question == i),
  x = ~sampleSize, y = ~jointRatio, color = ~method, type = "bar", name = ~paste("method", method)
) %>%
  layout(title = paste("Joint Coverage Ratio for", "Question", i), 
         yaxis = list(title = "Joint Coverage Ratio", range = c(0.9, 1),dtick = 0.01))
```


# Question 2 Individual

### Ratio

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.46, 0.44, 0.10)))
```

```{r}
knitr::kable(tibble(r = paste0("r", 1:3), value = c(0.34, 0.33, 0.33)))
```

```{r}
knitr::kable(tibble(delta = paste("delta", 1:3), value = c(0.02, 0.36, 0.34)))
```

Row
-----------------------------------------------------------------------

### 

```{r}
i <- 1
tval <- tvals[1]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  type = "bar", name = ~paste("Mix:", mixRatio)
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```

### 

```{r}

tval <- tvals[2]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  name = ~paste("Mix:", mixRatio), type = "bar"
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```

### 

```{r}

tval <- tvals[3]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  name = ~paste("Mix:", mixRatio), type = "bar"
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```

Row
-----------------------------------------------------------------------


### 

```{r}
i <- 2
tval <- tvals[1]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  name = ~paste("Mix:", mixRatio), type = "bar"
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```

### 

```{r}

tval <- tvals[2]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  name = ~paste("Mix:", mixRatio), type = "bar"
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```

### 

```{r}

tval <- tvals[3]

plot_ly(df2 %>% filter(trueValue == tval, method == i),
  x = ~sampleSize, y = ~coverRatio, color = ~mixRatio,
  name = ~paste("Mix:", mixRatio), type = "bar"
) %>%
  layout(title = paste("Original true Value:", tval, "\t Method", i), yaxis = list(title = "Coverage Ratio"))
```


# Question 2 Joint


### Ratio

```{r}
knitr::kable(tibble(p = paste0("p", 1:3), value = c(0.46, 0.44, 0.10)))
```

```{r}
knitr::kable(tibble(r = paste0("r", 1:3), value = c(0.34, 0.33, 0.33)))
```

```{r}
knitr::kable(tibble(delta = paste("delta", 1:3), value = c(0.02, 0.36, 0.34)))
```

Column
-----------------------------------------------------------------------

### Method 1

```{r}
i <- 1
plot_ly(
  data = dfjoint2 %>% filter(method == i),
  x = ~sampleSize, y = ~jointRatio, color = ~mixRatio, type = "bar", name = ~paste("MixRatio", mixRatio)
) %>%
  layout(title = paste("Joint Coverage Ratio for", "Method", i), yaxis = list(title = "Joint Coverage Ratio"))
```

Column
-----------------------------------------------------------------------

### Method 2

```{r}

i <- 2
plot_ly(
  data = dfjoint2 %>% filter(method == i),
  x = ~sampleSize, y = ~jointRatio, color = ~mixRatio, type = "bar", text=~jointRatio,textposition="top",
  name = ~paste("MixRatio", mixRatio)) %>%
  layout(title = paste("Joint Coverage Ratio for", "Method", i), yaxis = list(title = "Joint Coverage Ratio"))
```

# Summary 

Column {data-width=600}
-------------------------------------

### Summary

#### Goal: Construct simultaneous 95% confidence intervals


#### 1. Without contamination

#### Method 1:

* The coverage ratios are similar to each individual pair difference. And they are way over 95%.  
* The joint coverage ratio is also much higher than the target 95%.
* Too conservative. Increasing sample size is making it even more conservative. 

#### Method 2: 

* The coverage ratios are not constant over all pair differences. One of the three pair difference would have distinct lower coverage ratio than others.
* That relatively low coverage pair difference caps the joint coverage ratio, leading to the desired 95%.
* Relatively exact. Increasing sample may lower the ratio to target.



#### 2. With contamination

#### Individual Coverage:

Both methods show similiar patterns:

__The more pair difference diverage to its original value, the more it tends to be affected by the mix ratio.__

* true value 0.02: almost same before and after contamination -> limited impact
* true value 0.36: decreasing to 0.01 (completely replaced) -> most serious impact

#### Joint Coverage

Overall, method 2 has better performance than method 1.

   
Column {data-width=400}
-------------------------------------

### Joint coverage for data {data-height=200}
```{r}

tmp = dfjoint1 %>% select(-mixRatio) %>% mutate(method=paste0("method_",method))
tmp = tmp %>% spread(method,jointRatio) %>% arrange(question)
knitr::kable(tmp %>% mutate(close2target = ifelse(method_2<=method_1,"method 2","method 1")))
```


### Joint coverage for mixed data
```{r}
tmp = dfjoint2 %>% select(-question) %>% mutate(method=paste0("method_",method))
tmp = tmp %>% spread(method,jointRatio) %>% arrange(sampleSize)

knitr::kable(tmp %>% mutate(higherCoverRatio = ifelse(method_2>=method_1,"method 2","method 1")))
```
